# Mocha options
# https://mochajs.org/#configuring-mocha-nodejs
# https://github.com/mochajs/mocha/blob/master/example/config/.mocharc.yml


spec:
  # Test fixtures
  - test/fixtures/**/*.js

  # Test specs
  - test/specs/**/*.spec.js

# Abort after first test failure
bail: true
